import type { Metadata } from "next";
import { Dela_Gothic_One, Roboto } from "next/font/google";
import "./globals.scss";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";

const delatGothicOne = Dela_Gothic_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-dela",
});

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Grafit.Athletic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${roboto.variable} ${delatGothicOne.variable}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
